const seed={week:[["니트·카디건","이번 주 핵심","초가을~가을 전환기에 우선 확인. 비슷한 조직감·핏은 대표 상품만 남깁니다."],["가벼운 재킷","5개 후보","방송에서 코디 설명이 쉽고 단가가 과하지 않은 상품 우선."],["베스트·레이어드","4개 후보","FOX 고객이 기존 옷과 함께 입기 쉬운 디자인 우선."],["블라우스·셔츠","4개 후보","얼굴이 밝아 보이고 체형 부담이 적은 핏 우선."],["팬츠","4개 후보","허리 편안함과 실측 확인을 우선."],["원피스·스커트","3개 후보","한 벌만으로 방송 포인트가 되는 상품 위주."]],china:[["1688","도매 조사","가격·MOQ·판매자 조건이 실제 페이지에서 확인된 상품만 후보로 기록."],["VVIC","광저우 여성복","의류 전문 후보를 찾아 1688과 디자인·가격 중복 비교."],["Taobao","트렌드 참고","소매 반응과 스타일 탐색용. 도매 사입가는 별도 검증."]],korea:[["동대문 비교","중복 방지","중국 후보와 동대문에서 흔한 상품을 비교해 과다 사입을 줄임."],["계절 필터","지금+4주","지금 판매할 상품과 2~4주 뒤 상품을 분리."]],fox:[["FOX 고객 필터","40~50대","세련되고 편안하며 방송에서 장점을 설명하기 쉬운 상품 우선."],["판매 피드백","누적 학습","사입 판단과 실제 판매 결과를 다음 추천에 반영."]]};let tab="week",state=JSON.parse(localStorage.getItem("foxPick")||"{}");function card(x,k){let s=state[k]||"";return `<article class="card"><span class="tag">${x[1]}</span><h3>${x[0]}</h3><p>${x[2]}</p><div class="actions"><button class="buy" onclick="pick('${k}','buy')">✓ 사입${s=="buy"?" ●":""}</button><button class="hold" onclick="pick('${k}','hold')">보류${s=="hold"?" ●":""}</button><button class="no" onclick="pick('${k}','no')">제외${s=="no"?" ●":""}</button></div></article>`}function render(){const c=document.querySelector("#content");if(tab=="mine"){const all=[];Object.keys(seed).forEach(t=>seed[t].forEach((x,i)=>{let k=t+i;if(state[k]=="buy")all.push(card(x,k))}));c.innerHTML=all.length?all.join(""):'<div class="note"><b>아직 사입 선택이 없어요.</b><p>상품에서 ✓ 사입을 누르면 여기에 모입니다.</p></div>'}else c.innerHTML=seed[tab].map((x,i)=>card(x,tab+i)).join("");counts()}function pick(k,v){state[k]=v;localStorage.setItem("foxPick",JSON.stringify(state));render()}function counts(){buyN.textContent=Object.values(state).filter(x=>x=="buy").length;holdN.textContent=Object.values(state).filter(x=>x=="hold").length;noN.textContent=Object.values(state).filter(x=>x=="no").length}document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelector(".on")?.classList.remove("on");b.classList.add("on");tab=b.dataset.tab;render()});let deferred;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;installBtn.hidden=true}};render();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");

// FOX Producer v0.3 — 실제 상품 후보 데이터 구조
const productStore=JSON.parse(localStorage.getItem("foxProducts")||"[]");
function addProduct(p){productStore.push({id:"p"+Date.now(),name:p.name||"상품 후보",source:p.source||"",price:p.price||"",moq:p.moq||"",url:p.url||"",image:p.image||"",reason:p.reason||"",risk:p.risk||"",status:""});localStorage.setItem("foxProducts",JSON.stringify(productStore))}
function productCard(p){return `<article class="card product">${p.image?`<img class="pimg" src="${p.image}" alt="">`:""}<div><span class="tag">${p.source||"소싱 후보"}</span><h3>${p.name}</h3><p><b>가격</b> ${p.price||"확인 중"} · <b>MOQ</b> ${p.moq||"확인 중"}</p><p>${p.reason||"FOX 적합성 분석 예정"}</p>${p.risk?`<p class="risk">⚠ ${p.risk}</p>`:""}${p.url?`<p><a href="${p.url}" target="_blank" rel="noopener">원문 상품 보기 ↗</a></p>`:""}</div></article>`}
function renderProducts(){return productStore.length?productStore.map(productCard).join(""):'<div class="note"><b>실상품 후보 수집 준비 완료</b><p>확인된 상품만 사진·가격·MOQ·원문 링크와 함께 여기에 들어옵니다. 확인되지 않은 가격이나 판매량은 만들지 않습니다.</p></div>'}


const verifiedProducts=[
{id:"vvic-a101406",name:"V넥 루즈핏 스트라이프 니트 카디건",source:"VVIC · 광저우",price:"¥52",moq:"페이지 수량 선택 기준 확인",url:"https://global.vvic.com/products/6a8af1c1f99de7000739ca68",reason:"블랙/그레이, 루즈핏이라 FOX 고객층에 비교적 적용하기 쉬운 후보.",risk:"폴리에스터 100%, 프리사이즈라 실측 확인 필요"},
{id:"vvic-x1007",name:"빅사이즈 복고 니트 카디건",source:"VVIC · 광저우",price:"¥26",moq:"페이지 수량 선택 기준 확인",url:"https://global.vvic.com/products/6967422a90a91a000765b855",reason:"빅사이즈 표기와 브라운·블랙·그레이 계열로 FOX 체형 커버 후보.",risk:"프리사이즈 표기와 빅사이즈 표현이 함께 있어 실제 실측 필수"},
{id:"vvic-a10191",name:"컬러 네프사 니트 카디건",source:"VVIC · 광저우",price:"¥42",moq:"페이지 수량 선택 기준 확인",url:"https://global.vvic.com/products/6a86d96774b9ba000665286c",reason:"오트밀·올리브·브라운 등 가을 방송에서 색상 선택지가 좋은 후보.",risk:"슬림핏 표기라 FOX 고객층 체형 적합성 샘플 확인 필요"},
{id:"vvic-64535",name:"울 100% 라운드 카디건",source:"VVIC · 광저우",price:"¥45",moq:"페이지 수량 선택 기준 확인",url:"https://global.vvic.com/products/6a66009174b9ba00067e5a7e",reason:"S~2XL 사이즈와 그레이·카키 등 성숙한 컬러 구성이 강점.",risk:"페이지의 울100% 소재 표기는 샘플/라벨 재확인 권장"},
{id:"vvic-a10014",name:"루즈 드롭숄더 스트라이프 니트",source:"VVIC · 광저우",price:"¥39",moq:"페이지 수량 선택 기준 확인",url:"https://global.vvic.com/products/6a85bdb7a917210006ae877d",reason:"루즈 실루엣과 브라운·블랙 계열로 데일리 판매 후보.",risk:"프리사이즈이므로 가슴단면·총장 확인 필요"},
{id:"vvic-a10151",name:"니트 카디건 + 원피스 2피스",source:"VVIC · 광저우",price:"¥73",moq:"페이지 수량 선택 기준 확인",url:"https://global.vvic.com/products/6a86d98d74b9ba00066528cd",reason:"한 세트로 코디가 완성돼 라이브 설명과 객단가 구성에 활용 가능한 후보.",risk:"M/L만 확인되어 사이즈 범위가 좁을 수 있음"}
];
if(!localStorage.getItem("foxVerifiedSeed20260925")){verifiedProducts.forEach(p=>{if(!productStore.some(x=>x.id===p.id))productStore.push({...p,status:""})});localStorage.setItem("foxProducts",JSON.stringify(productStore));localStorage.setItem("foxVerifiedSeed20260925","1")}


// v0.4 후보 검색/중복 경고/메모/내보내기
function norm(s){return (s||"").toLowerCase().replace(/\s+/g,"")}
function duplicateGroups(){const words=["니트","카디건","재킷","베스트","블라우스","셔츠","팬츠","원피스","스커트"];return words.map(w=>({w,items:productStore.filter(p=>norm(p.name).includes(w))})).filter(g=>g.items.length>1)}
function exportPicks(){const rows=[["상품","출처","가격","MOQ","상태","링크"],...productStore.map(p=>[p.name,p.source,p.price,p.moq,p.status||"",p.url])];const csv=rows.map(r=>r.map(v=>'"'+String(v||"").replaceAll('"','""')+'"').join(",")).join("\n");const b=new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="FOX_사입후보.csv";a.click();URL.revokeObjectURL(a.href)}
function saveMemo(id,val){localStorage.setItem("foxMemo:"+id,val)}
function getMemo(id){return localStorage.getItem("foxMemo:"+id)||""}
function productCardV2(p){const dup=duplicateGroups().find(g=>g.items.some(x=>x.id===p.id));return `<article class="card product">${p.image?`<img class="pimg" src="${p.image}" alt="">`:""}<span class="tag">${p.source||"소싱 후보"}</span>${dup?`<span class="dupe">중복 후보 ${dup.items.length}</span>`:""}<h3>${p.name}</h3><p><b>가격</b> ${p.price||"확인 중"} · <b>MOQ</b> ${p.moq||"확인 중"}</p><p>${p.reason||""}</p>${p.risk?`<p class="risk">⚠ ${p.risk}</p>`:""}<textarea placeholder="사입 메모" oninput="saveMemo('${p.id}',this.value)">${getMemo(p.id)}</textarea>${p.url?`<p><a href="${p.url}" target="_blank" rel="noopener">원문 상품 보기 ↗</a></p>`:""}</article>`}


// v0.5 실제 후보 화면 연결
function showSourcedProducts(query=""){const q=norm(query);const list=productStore.filter(p=>!q||norm([p.name,p.source,p.reason,p.price].join(" ")).includes(q));content.innerHTML=list.length?list.map(productCardV2).join(""):'<div class="note"><b>검색 결과가 없습니다.</b></div>'}
if(typeof exportBtn!=="undefined")exportBtn.onclick=exportPicks;
if(typeof searchBox!=="undefined")searchBox.addEventListener("input",e=>showSourcedProducts(e.target.value));
document.querySelectorAll('nav button').forEach(b=>b.addEventListener("click",()=>{if(b.dataset.tab==="china")setTimeout(()=>showSourcedProducts(searchBox?.value||""),0)}));


// v0.6 상품별 의사결정 + 예상원가 메모
function setProductStatus(id,status){const p=productStore.find(x=>x.id===id);if(!p)return;p.status=status;localStorage.setItem("foxProducts",JSON.stringify(productStore));showSourcedProducts(searchBox?.value||"")}
function setCost(id,key,val){const p=productStore.find(x=>x.id===id);if(!p)return;p[key]=val;localStorage.setItem("foxProducts",JSON.stringify(productStore))}
function productCardV3(p){const dup=duplicateGroups().find(g=>g.items.some(x=>x.id===p.id));return `<article class="card product">${p.image?`<img class="pimg" src="${p.image}" alt="">`:""}<span class="tag">${p.source||"소싱 후보"}</span>${dup?`<span class="dupe">중복 ${dup.items.length}</span>`:""}<h3>${p.name}</h3><p><b>도매가</b> ${p.price||"확인 중"} · <b>MOQ</b> ${p.moq||"확인 중"}</p><p>${p.reason||""}</p>${p.risk?`<p class="risk">⚠ ${p.risk}</p>`:""}<div class="costs"><input inputmode="numeric" placeholder="예상 원가(원)" value="${p.krwCost||""}" onchange="setCost('${p.id}','krwCost',this.value)"><input inputmode="numeric" placeholder="예상 판매가(원)" value="${p.sellPrice||""}" onchange="setCost('${p.id}','sellPrice',this.value)"></div><textarea placeholder="사입 메모" oninput="saveMemo('${p.id}',this.value)">${getMemo(p.id)}</textarea><div class="actions"><button class="buy" onclick="setProductStatus('${p.id}','buy')">✓ 사입 ${p.status==="buy"?"●":""}</button><button class="hold" onclick="setProductStatus('${p.id}','hold')">보류 ${p.status==="hold"?"●":""}</button><button class="no" onclick="setProductStatus('${p.id}','no')">제외 ${p.status==="no"?"●":""}</button></div>${p.url?`<p><a href="${p.url}" target="_blank" rel="noopener">원문 상품 보기 ↗</a></p>`:""}</article>`}
function showSourcedProductsV3(query=""){const q=norm(query);const list=productStore.filter(p=>!q||norm([p.name,p.source,p.reason,p.price].join(" ")).includes(q));content.innerHTML=list.length?list.map(productCardV3).join(""):'<div class="note"><b>검색 결과가 없습니다.</b></div>';productCounts()}
function productCounts(){const b=productStore.filter(x=>x.status==="buy").length,hh=productStore.filter(x=>x.status==="hold").length,n=productStore.filter(x=>x.status==="no").length;if(typeof buyN!=="undefined")buyN.textContent=b;if(typeof holdN!=="undefined")holdN.textContent=hh;if(typeof noN!=="undefined")noN.textContent=n}
if(typeof searchBox!=="undefined")searchBox.addEventListener("input",e=>showSourcedProductsV3(e.target.value));
document.querySelectorAll('nav button').forEach(b=>b.addEventListener("click",()=>{if(b.dataset.tab==="china")setTimeout(()=>showSourcedProductsV3(searchBox?.value||""),10)}));
productCounts();


// v0.7 FOX 수익 계산 + 사입 선택 전용 보기
function n(v){return Number(String(v||"").replace(/[^0-9.]/g,""))||0}
function marginInfo(p){const cost=n(p.krwCost),sell=n(p.sellPrice);if(!cost||!sell)return "";const profit=sell-cost,rate=Math.round(profit/sell*100);return `<div class="margin"><b>예상 마진</b> ${profit.toLocaleString()}원 · ${rate}%</div>`}
function selectedProducts(){return productStore.filter(p=>p.status==="buy")}
function showMySourcing(){const list=selectedProducts();content.innerHTML=list.length?'<div class="note"><b>내 사입 후보 '+list.length+'개</b><p>최종 사입 전에 중복과 예상원가를 한 번 더 확인하세요.</p></div>'+list.map(productCardV4).join(""):'<div class="note"><b>아직 선택한 실상품이 없습니다.</b></div>';productCounts()}
function productCardV4(p){const dup=duplicateGroups().find(g=>g.items.some(x=>x.id===p.id));return `<article class="card product">${p.image?`<img class="pimg" src="${p.image}" alt="">`:""}<span class="tag">${p.source||"소싱 후보"}</span>${dup?`<span class="dupe">중복 ${dup.items.length}</span>`:""}<h3>${p.name}</h3><p><b>도매가</b> ${p.price||"확인 중"} · <b>MOQ</b> ${p.moq||"확인 중"}</p><p>${p.reason||""}</p>${p.risk?`<p class="risk">⚠ ${p.risk}</p>`:""}<div class="costs"><input inputmode="numeric" placeholder="예상 원가(원)" value="${p.krwCost||""}" onchange="setCost('${p.id}','krwCost',this.value);showSourcedProductsV4(searchBox?.value||'')"><input inputmode="numeric" placeholder="예상 판매가(원)" value="${p.sellPrice||""}" onchange="setCost('${p.id}','sellPrice',this.value);showSourcedProductsV4(searchBox?.value||'')"></div>${marginInfo(p)}<textarea placeholder="사입 메모" oninput="saveMemo('${p.id}',this.value)">${getMemo(p.id)}</textarea><div class="actions"><button class="buy" onclick="setProductStatus('${p.id}','buy')">✓ 사입 ${p.status==="buy"?"●":""}</button><button class="hold" onclick="setProductStatus('${p.id}','hold')">보류 ${p.status==="hold"?"●":""}</button><button class="no" onclick="setProductStatus('${p.id}','no')">제외 ${p.status==="no"?"●":""}</button></div>${p.url?`<p><a href="${p.url}" target="_blank" rel="noopener">원문 상품 보기 ↗</a></p>`:""}</article>`}
function showSourcedProductsV4(query=""){const q=norm(query);const list=productStore.filter(p=>!q||norm([p.name,p.source,p.reason,p.price].join(" ")).includes(q));content.innerHTML=list.length?list.map(productCardV4).join(""):'<div class="note"><b>검색 결과가 없습니다.</b></div>';productCounts()}
document.querySelectorAll('nav button').forEach(b=>b.addEventListener("click",()=>{if(b.dataset.tab==="china")setTimeout(()=>showSourcedProductsV4(searchBox?.value||""),20);if(b.dataset.tab==="mine")setTimeout(showMySourcing,20)}));
